In [1]:
import numpy as np

In [2]:
np.zeros((6,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [5]:
np.empty((5,8)).dtype

dtype('float64')

In [12]:
array1 = np.array([[5,8,9,66,2],[44,88,99,32,4]])
print(array1)

[[ 5  8  9 66  2]
 [44 88 99 32  4]]


In [13]:
array1*array1

array([[  25,   64,   81, 4356,    4],
       [1936, 7744, 9801, 1024,   16]])

In [14]:
array1+array1

array([[ 10,  16,  18, 132,   4],
       [ 88, 176, 198,  64,   8]])

In [15]:
array1/array1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])