In [1]:
import numpy as np

In [19]:
a = np.array([56,44,89,26,54,77,158,77,45,23,52,5,95,4,4,6,5,88,45,69,6633,225,412,45,22,52,252,11])

In [20]:
np.argsort(a)

array([13, 14, 16, 11, 15, 27, 24,  9,  3,  1,  8, 23, 18, 25, 10,  4,  0,
       19,  7,  5, 17,  2, 12,  6, 21, 26, 22, 20], dtype=int64)

In [21]:
np.argmin(a)

13

In [22]:
np.argmax(a)

20

In [24]:
len(a)

28

In [25]:
a= a.reshape(4,7)

In [26]:
a

array([[  56,   44,   89,   26,   54,   77,  158],
       [  77,   45,   23,   52,    5,   95,    4],
       [   4,    6,    5,   88,   45,   69, 6633],
       [ 225,  412,   45,   22,   52,  252,   11]])

In [27]:
np.argsort(a)

array([[3, 1, 4, 0, 5, 2, 6],
       [6, 4, 2, 1, 3, 0, 5],
       [0, 2, 1, 4, 5, 3, 6],
       [6, 3, 2, 4, 0, 5, 1]], dtype=int64)

In [28]:
np.argsort(a,axis=0)

array([[2, 2, 2, 3, 1, 2, 1],
       [0, 0, 1, 0, 2, 0, 3],
       [1, 1, 3, 1, 3, 1, 0],
       [3, 3, 0, 2, 0, 3, 2]], dtype=int64)